services:
  db:
    image: postgres:15-alpine
    container_name: metrica_db_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5433:5432"
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: metrica_api_prod
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: metrica_web_prod
    ports:
      - "3001:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
